### ISSUE TITLE
API Call: Social Login/Signup

### ISSUE THREAD

**Issue by LauraWebdev** [LauraWebdev/mgg-server#16]
Create an oauth login backend and handle registration/login.

Providers:
- Discord
- Twitter
- Google

**Comment by Cheesire** [comment]
Will you also be able to login using your username if you already have an account?

**Comment by LauraWebdev** [comment]
The system currently already features a simple username/password registration/login. This is only for additional login methods

**Comment by Cheesire** [comment]
ok thx
