### ISSUE TITLE
Require people to provide in-game screenshots?

### ISSUE THREAD

**Issue by mariomadproductions** [LauraWebdev/mgg-server#29]
It seems like a lot of people are not including an image, or if they do, its not an actual in-game screenshot. Maybe a rule should be added that you have to include an actual in-game screenshot?

**Comment by LauraWebdev** [comment]
We thought about this in pre-production, however we decided against it as it would only shift the problem towards people uploading random images/spam screenshots to our server.

You could give creators a notice on the comment section that their game doesn't look too flattering without a screenshot.

**Comment by mariomadproductions** [comment]
Yeah, I guess it might also put-off people from using the site.

Maybe just adding some text to the upload page suggesting that the user uploads a proper screenshot?

And/or entries could be flagged by users as having not having a proper screenshot, and those could be filtered out of search results?

**Comment by LauraWebdev** [comment]
There is actually text on successful creation of a game that prompts the user to upload some screenshots

**Comment by mariomadproductions** [comment]
Ah, I didn't get far enough into the submission process to see that.
